### ISSUE TITLE
export_header.py error

### ISSUE THREAD

**Issue by jpiwek** [MicrochipTech/mbedtls-examples#4]
Hi Bryan,

seems like export_header.py throws an exception at line 57

PS C:\development\git\mbedtls-examples\scripts> py .\export_header.py --root .\root-ca.crt --signer .\signer-ca.crt --device .\d012357B96F853E43EE_0.crt
Traceback (most recent call last):
  File ".\export_header.py", line 86, in <module>
    create_output_file(args.out, args.root, args.device, args.signer)
  File ".\export_header.py", line 57, in create_output_file
    root_key_bytes = root_cert.public_key().public_bytes(serialization.Encoding.X962, serialization.PublicFormat.UncompressedPoint)
  File "C:\Users\jpiwe\AppData\Local\Programs\Python\Python36-32\lib\enum.py", line 324, in __getattr__
    raise AttributeError(name) from None
AttributeError: X962

**Comment by bryan-hunt** [comment]
The module “cryptography” needs to be updated.

See requirements.txt

**Comment by jpiwek** [comment]
thanks! now it works!
